version: "3.8"
services:
  db:
    build: ./db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: abc123
  redis-server:
    image: redis
  application:
    build: ./application
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    volumes:
      - /app/node_modules
      - ./application:/app
    environment: 
      - CHOKIDAR_USEPOLLING=true
    

